language: scala #testhttp://downloads.typesafe.com/play/2.2.2/play-2.2.2.zip
env:
  - PLAY_VERSION=2.2.2
before_script: 
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test